/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package network.randomizer.internal;

import java.awt.Component;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.cytoscape.application.CyApplicationManager;
import org.cytoscape.application.swing.CySwingApplication;
import org.cytoscape.application.swing.CytoPanelComponent;
import org.cytoscape.application.swing.CytoPanelName;

/**
 *
 * @author gabriele
 */
public class OptionsMenu extends javax.swing.JPanel implements CytoPanelComponent {
    
    private RandomizerCore randomizerCore;
    public CyApplicationManager cyApplicationManager;
    public CySwingApplication cyDesktopService;
    public CyActivator cyActivator;
    public ThreadEngine thread;
    private final boolean notselected = false;


    /**
     * Creates new form OptionsMenuNew
     */
    public OptionsMenu(RandomizerCore core) {
        initComponents();
        cyActivator = core.cyActivator;
        cyApplicationManager = core.cyApplicationManager;
        cyDesktopService = core.cyDesktopService;
        randomizerCore = core;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ERGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        StartButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ERPanel = new javax.swing.JPanel();
        ERtxtN = new javax.swing.JTextField();
        lblN = new javax.swing.JLabel();
        ERtxtP = new javax.swing.JTextField();
        lblP = new javax.swing.JLabel();
        ERtxtM = new javax.swing.JTextField();
        lblM = new javax.swing.JLabel();
        ERrbNpType = new javax.swing.JRadioButton();
        ERrbNMType = new javax.swing.JRadioButton();
        ERRandomizeCurrent = new javax.swing.JCheckBox();
        ERCheck = new javax.swing.JCheckBox();
        ERhelp = new javax.swing.JButton();
        WSPanel = new javax.swing.JPanel();
        WStxtN = new javax.swing.JTextField();
        lblN1 = new javax.swing.JLabel();
        WStxtK = new javax.swing.JTextField();
        lblP1 = new javax.swing.JLabel();
        WStxtBeta = new javax.swing.JTextField();
        lblM1 = new javax.swing.JLabel();
        WSCheck = new javax.swing.JCheckBox();
        WShelp = new javax.swing.JButton();
        multiPanel = new javax.swing.JPanel();
        multiRandomizeCurrent = new javax.swing.JCheckBox();
        multiIsDirected = new javax.swing.JCheckBox();
        multiCheck = new javax.swing.JCheckBox();
        MULTIhelp = new javax.swing.JButton();
        WSPanel1 = new javax.swing.JPanel();
        BAtxtN = new javax.swing.JTextField();
        lblN2 = new javax.swing.JLabel();
        BAtxtM = new javax.swing.JTextField();
        lblP2 = new javax.swing.JLabel();
        BACheck = new javax.swing.JCheckBox();
        BAHelp = new javax.swing.JButton();
        lblP3 = new javax.swing.JLabel();
        WSPanel2 = new javax.swing.JPanel();
        LATtxtDimSizes = new javax.swing.JTextField();
        lblP4 = new javax.swing.JLabel();
        LATCheck = new javax.swing.JCheckBox();
        LATHelp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LATisTorus = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(480, 640));
        setRequestFocusEnabled(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(320, 600));
        jScrollPane1.setRequestFocusEnabled(false);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setPreferredSize(new java.awt.Dimension(365, 845));
        jPanel1.setRequestFocusEnabled(false);

        StartButton.setText("START");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Networks Randomizer");

        ERPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblN.setText("n = ");

        lblP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblP.setText("p = ");

        lblM.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblM.setText("M = ");

        ERGroup.add(ERrbNpType);
        ERrbNpType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ERrbNpType.setText("G(n,p)");
        ERrbNpType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERrbNpTypeActionPerformed(evt);
            }
        });

        ERGroup.add(ERrbNMType);
        ERrbNMType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ERrbNMType.setText("G(n,M)");
        ERrbNMType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERrbNMTypeActionPerformed(evt);
            }
        });

        ERRandomizeCurrent.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ERRandomizeCurrent.setText("Randomize current network");
        ERRandomizeCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERRandomizeCurrentActionPerformed(evt);
            }
        });

        ERCheck.setText("Erdõs–Rényi model");
        ERCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERCheckActionPerformed(evt);
            }
        });

        ERhelp.setText("?");
        ERhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERhelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ERPanelLayout = new javax.swing.GroupLayout(ERPanel);
        ERPanel.setLayout(ERPanelLayout);
        ERPanelLayout.setHorizontalGroup(
            ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ERPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ERPanelLayout.createSequentialGroup()
                        .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ERrbNMType)
                            .addComponent(ERrbNpType))
                        .addGap(18, 18, 18)
                        .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ERPanelLayout.createSequentialGroup()
                                .addComponent(lblM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ERtxtM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ERPanelLayout.createSequentialGroup()
                                    .addComponent(lblN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ERtxtN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ERPanelLayout.createSequentialGroup()
                                    .addComponent(lblP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ERtxtP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ERPanelLayout.createSequentialGroup()
                        .addComponent(ERRandomizeCurrent)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(ERPanelLayout.createSequentialGroup()
                .addComponent(ERCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ERhelp)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ERPanelLayout.setVerticalGroup(
            ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ERPanelLayout.createSequentialGroup()
                .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ERCheck)
                    .addComponent(ERhelp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ERRandomizeCurrent)
                .addGap(18, 18, 18)
                .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ERtxtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN))
                .addGap(18, 18, 18)
                .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ERPanelLayout.createSequentialGroup()
                        .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP)
                            .addComponent(ERtxtP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(ERPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ERtxtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblM)
                            .addComponent(ERrbNMType)))
                    .addComponent(ERrbNpType))
                .addGap(19, 19, 19))
        );

        WSPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WSPanel.setFocusCycleRoot(true);

        lblN1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblN1.setText("N = ");

        lblP1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblP1.setText("K = ");

        lblM1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblM1.setText("<html>&beta = </html>");

        WSCheck.setText("Watt-Strogatz model");
        WSCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WSCheckActionPerformed(evt);
            }
        });

        WShelp.setText("?");
        WShelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WShelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WSPanelLayout = new javax.swing.GroupLayout(WSPanel);
        WSPanel.setLayout(WSPanelLayout);
        WSPanelLayout.setHorizontalGroup(
            WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSPanelLayout.createSequentialGroup()
                .addGroup(WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WSPanelLayout.createSequentialGroup()
                        .addComponent(WSCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WShelp))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WSPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WSPanelLayout.createSequentialGroup()
                                .addComponent(lblP1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WStxtK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WSPanelLayout.createSequentialGroup()
                                .addComponent(lblN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WStxtN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WSPanelLayout.createSequentialGroup()
                                .addComponent(lblM1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WStxtBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(150, 151, Short.MAX_VALUE))
        );
        WSPanelLayout.setVerticalGroup(
            WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSPanelLayout.createSequentialGroup()
                .addGroup(WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WSCheck)
                    .addComponent(WShelp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WStxtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP1)
                    .addComponent(WStxtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WStxtBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        multiPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        multiRandomizeCurrent.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        multiRandomizeCurrent.setText("Get parameters from current network");

        multiIsDirected.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        multiIsDirected.setText("is directed");

        multiCheck.setText("Multiplication model");
        multiCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiCheckActionPerformed(evt);
            }
        });

        MULTIhelp.setText("?");

        javax.swing.GroupLayout multiPanelLayout = new javax.swing.GroupLayout(multiPanel);
        multiPanel.setLayout(multiPanelLayout);
        multiPanelLayout.setHorizontalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiRandomizeCurrent)
                    .addComponent(multiIsDirected))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(multiPanelLayout.createSequentialGroup()
                .addComponent(multiCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MULTIhelp)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        multiPanelLayout.setVerticalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiPanelLayout.createSequentialGroup()
                .addGroup(multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiCheck)
                    .addComponent(MULTIhelp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(multiRandomizeCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(multiIsDirected)
                .addGap(220, 220, 220))
        );

        WSPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblN2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblN2.setText("N = ");

        lblP2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblP2.setText("m = ");

        BACheck.setText("Barabási-Albert model");
        BACheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACheckActionPerformed(evt);
            }
        });

        BAHelp.setText("?");
        BAHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAHelpActionPerformed(evt);
            }
        });

        lblP3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblP3.setText("<< N");

        javax.swing.GroupLayout WSPanel1Layout = new javax.swing.GroupLayout(WSPanel1);
        WSPanel1.setLayout(WSPanel1Layout);
        WSPanel1Layout.setHorizontalGroup(
            WSPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSPanel1Layout.createSequentialGroup()
                .addGroup(WSPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WSPanel1Layout.createSequentialGroup()
                        .addComponent(BACheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BAHelp))
                    .addGroup(WSPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(WSPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(WSPanel1Layout.createSequentialGroup()
                                .addComponent(lblP2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BAtxtM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WSPanel1Layout.createSequentialGroup()
                                .addComponent(lblN2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BAtxtN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblP3)))
                .addGap(0, 143, Short.MAX_VALUE))
        );
        WSPanel1Layout.setVerticalGroup(
            WSPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSPanel1Layout.createSequentialGroup()
                .addGroup(WSPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BACheck)
                    .addComponent(BAHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(WSPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAtxtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WSPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP2)
                    .addComponent(BAtxtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP3))
                .addContainerGap())
        );

        WSPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblP4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblP4.setText("Dimensions sizes:");

        LATCheck.setText("Lattice model");

        LATHelp.setText("?");
        LATHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LATHelpActionPerformed(evt);
            }
        });

        jLabel2.setText("separated by comma (e.g., \"2,3,2\")");

        LATisTorus.setText("Generate hyper torus");

        javax.swing.GroupLayout WSPanel2Layout = new javax.swing.GroupLayout(WSPanel2);
        WSPanel2.setLayout(WSPanel2Layout);
        WSPanel2Layout.setHorizontalGroup(
            WSPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSPanel2Layout.createSequentialGroup()
                .addComponent(LATCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LATHelp)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(WSPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WSPanel2Layout.createSequentialGroup()
                        .addComponent(lblP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LATtxtDimSizes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WSPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(WSPanel2Layout.createSequentialGroup()
                        .addComponent(LATisTorus)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        WSPanel2Layout.setVerticalGroup(
            WSPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSPanel2Layout.createSequentialGroup()
                .addGroup(WSPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LATCheck)
                    .addComponent(LATHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(WSPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP4)
                    .addComponent(LATtxtDimSizes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LATisTorus)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(WSPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ERPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WSPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WSPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ERPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(WSPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("closing randomizer");
        closeRandomizer();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ERrbNpTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERrbNpTypeActionPerformed
        setERType();
    }//GEN-LAST:event_ERrbNpTypeActionPerformed

    private void ERrbNMTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERrbNMTypeActionPerformed
        setERType();
    }//GEN-LAST:event_ERrbNMTypeActionPerformed

    private void ERRandomizeCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERRandomizeCurrentActionPerformed
        boolean enabled = true;
        if(ERRandomizeCurrent.isSelected()) enabled = false;
        ERtxtN.setEnabled(enabled);
        ERrbNMType.setEnabled(enabled);
        ERrbNpType.setEnabled(enabled);
        ERtxtM.setEnabled(enabled);
        ERtxtP.setEnabled(enabled);
        if(enabled) setERType();
    }//GEN-LAST:event_ERRandomizeCurrentActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        if(ERCheck.isSelected()){
            System.out.println("You started an Erdos-Renyi model");
            AbstractModel randomizer;
            
            // randomize current network
            if(ERRandomizeCurrent.isSelected()){
                randomizer = new ErdosRenyiModel(randomizerCore);
            }
            
            // generate random network
            else{
                try {
                    int n = Integer.parseInt(ERtxtN.getText());
                    if(n < 0) throw new Exception("Parameter n less than zero!");
                    ErdosRenyiModel.ERType type;
                    // G(N,M) model is selected
                    if(ERrbNMType.isSelected()){
                        type = ErdosRenyiModel.ERType.nM;
                        int M = Integer.parseInt(ERtxtM.getText());
                        if(M < 0) throw new Exception("Parameter M less than zero!");
                        if(M > n*(n-1)/2) throw new Exception("Parameter M larger than possible number of edges!\nFor n = " + n + ", maximum M = " + (n*(n-1)/2) + ".");
                        randomizer = new ErdosRenyiModel(n, M, 0, type, randomizerCore);
                    }
                    // G(N,p) model is selected
                    else if(ERrbNpType.isSelected()){
                        type = ErdosRenyiModel.ERType.np;
                        float p = Float.parseFloat(ERtxtP.getText());
                        if(p < 0 || p > 1) throw new Exception("Parameter p out of  the range [0,1]!");
                        randomizer = new ErdosRenyiModel(n, 0, p, type, randomizerCore);
                    }
                    else{
                        throw new Exception("Type of Erdõs–Rényi model isn't selected. Choose one!");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this.cyDesktopService.getJFrame(),e.getMessage(), "Randomizer", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            thread = new ThreadEngine(randomizer);
            thread.start();            
        }
        
        if(WSCheck.isSelected()){
            System.out.println("You started a Watts-Strogatz model");
            AbstractModel randomizer;
            // generate random network
            try {
                int N = Integer.parseInt(WStxtN.getText());
                if(N < 0) throw new Exception("Parameter N less than zero!");
                int K = Integer.parseInt(WStxtK.getText());
                if(K < 0) throw new Exception("Parameter K less than zero!");
                if(K > N/2) throw new Exception("Parameter K must be less than N/2!");
                float beta = Float.parseFloat(WStxtBeta.getText());
                if(beta < 0 || beta > 1) throw new Exception("Parameter beta must be in [0,1]!");
                randomizer = new WattsStrogatzModel(randomizerCore, N, K, beta);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.cyDesktopService.getJFrame(),e.getMessage(), "Randomizer", JOptionPane.WARNING_MESSAGE);
                return;
            }
            thread = new ThreadEngine(randomizer);
            thread.start();
        }
        
        if(BACheck.isSelected()){
            System.out.println("You started a Barabasi-Albert model");
            AbstractModel randomizer;
            // generate random network
            try {
                int N = Integer.parseInt(BAtxtN.getText());
                if(N < 0) throw new Exception("Parameter N less than zero!");
                int m = Integer.parseInt(BAtxtM.getText());
                if(m < 0) throw new Exception("Parameter m less than zero!");
                if(m > N/2) throw new Exception("Parameter m too large!");
                randomizer = new BarabasiAlbertModel(randomizerCore, N, m);
            } catch (Exception e) {
                String message = e.getMessage();
                if(message.equals("")){
                    message = "Some arguments missing or of wrong format!";
                }
                JOptionPane.showMessageDialog(this.cyDesktopService.getJFrame(), message, "Randomizer", JOptionPane.WARNING_MESSAGE);
                return;
            }
            thread = new ThreadEngine(randomizer);
            thread.start();
        }
        
        if(LATCheck.isSelected()){
            System.out.println("You started a Random Lattice model");
            AbstractModel randomizer;
            // generate random network
            try {
                String[] stringDims = LATtxtDimSizes.getText().split(",");
                List<Integer> dims = new LinkedList<>();
                for(int i = 0; i < stringDims.length ; i++)
                    dims.add(Integer.parseInt(stringDims[i]));
                for (Integer dim : dims) {
                    if(dim < 1){
                        throw new Exception("All dimensions must be greater then 1.");
                    }
                }
                randomizer = new LatticeModel(randomizerCore, dims, LATisTorus.isSelected());
            } catch(NumberFormatException e){
                String message = "Wrong random lattice dimension sizes input format!\nPlease use comma seperated integer values only.";
                JOptionPane.showMessageDialog(this.cyDesktopService.getJFrame(), message, "Randomizer", JOptionPane.WARNING_MESSAGE);
                return;
            } catch (Exception e) {
                String message = e.getMessage();
                if(message.equals("")){
                    message = "Wrong random lattice dimension sizes input format!\nPlease use comma seperated integer values only.";
                }
                JOptionPane.showMessageDialog(this.cyDesktopService.getJFrame(), message, "Randomizer", JOptionPane.WARNING_MESSAGE);
                return;
            }
            thread = new ThreadEngine(randomizer);
            thread.start();
        }
        
        if(multiCheck.isSelected()){
            System.out.println("You started a Multiplication model");
            AbstractModel randomizer;            
            boolean direction = multiIsDirected.isSelected();//is the network directed???????
            System.out.println("direction "+direction);
            // using network randomization
            if(multiRandomizeCurrent.isSelected()) {
                if (cyApplicationManager.getCurrentNetworkView() == null){
                    JOptionPane.showMessageDialog(this.cyDesktopService.getJFrame(),"No views available for your network (is the network missing?)", "Randomizer", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    if(cyApplicationManager.getCurrentNetworkView().getModel().getNodeList().isEmpty()){
                        JOptionPane.showMessageDialog(this.cyDesktopService.getJFrame(),"The network contains zero nodes", "Randomizer", JOptionPane.WARNING_MESSAGE);
                    }
                    else{
                        randomizer = new MultiplicationModel(randomizerCore,direction);
                        thread = new ThreadEngine(randomizer);
                        thread.start();                        
                    }
                }
            }
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void ERCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERCheckActionPerformed
        // TODO add your handling code here:
        if(ERCheck.isSelected()){        
            WSCheck.setEnabled(notselected);
            multiCheck.setEnabled(notselected);
            multiPanel.setEnabled(notselected);
            WStxtN.setEnabled(notselected);
            WStxtK.setEnabled(notselected);
            WStxtBeta.setEnabled(notselected);
            multiRandomizeCurrent.setEnabled(notselected);
            multiIsDirected.setEnabled(notselected);        
        }
        else{
            WSCheck.setEnabled(!notselected);
            multiCheck.setEnabled(!notselected);
            multiPanel.setEnabled(!notselected);
            WStxtN.setEnabled(!notselected);
            WStxtK.setEnabled(!notselected);
            WStxtBeta.setEnabled(!notselected);
            multiRandomizeCurrent.setEnabled(!notselected);
            multiIsDirected.setEnabled(!notselected);
        }
    }//GEN-LAST:event_ERCheckActionPerformed

    private void WSCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WSCheckActionPerformed
        // TODO add your handling code here:
        if(WSCheck.isSelected()){
            ERCheck.setEnabled(notselected);
            ERRandomizeCurrent.setEnabled(notselected);
            multiCheck.setEnabled(notselected);multiPanel.setEnabled(notselected);
            ERtxtN.setEnabled(notselected);
            ERtxtM.setEnabled(notselected);
            ERtxtP.setEnabled(notselected);
            ERrbNpType.setEnabled(notselected);
            ERrbNMType.setEnabled(notselected);
            multiRandomizeCurrent.setEnabled(notselected);
            multiIsDirected.setEnabled(notselected);        
        }
        else{
            ERCheck.setEnabled(!notselected);
            ERRandomizeCurrent.setEnabled(!notselected);
            multiCheck.setEnabled(!notselected);
            multiPanel.setEnabled(!notselected);            
            ERrbNpType.setEnabled(!notselected);
            ERrbNMType.setEnabled(!notselected);
            ERtxtN.setEnabled(!notselected);
            ERtxtM.setEnabled(!notselected);
            ERtxtP.setEnabled(!notselected);
            multiRandomizeCurrent.setEnabled(!notselected);
            multiIsDirected.setEnabled(!notselected);
        }
    }//GEN-LAST:event_WSCheckActionPerformed

    private void multiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiCheckActionPerformed
        // TODO add your handling code here:
        if(multiCheck.isSelected()){
            ERCheck.setEnabled(notselected);
            ERRandomizeCurrent.setEnabled(notselected);
            WSCheck.setEnabled(notselected);
            WStxtN.setEnabled(notselected);
            WStxtK.setEnabled(notselected);
            WStxtBeta.setEnabled(notselected);            
            ERrbNpType.setEnabled(notselected);
            ERrbNMType.setEnabled(notselected);
            ERtxtN.setEnabled(notselected);
            ERtxtM.setEnabled(notselected);
            ERtxtP.setEnabled(notselected);
        }
        else{
            ERCheck.setEnabled(!notselected);
            ERRandomizeCurrent.setEnabled(!notselected);
            WSCheck.setEnabled(!notselected);
            WStxtN.setEnabled(!notselected);
            WStxtK.setEnabled(!notselected);
            WStxtBeta.setEnabled(!notselected);            
            ERrbNpType.setEnabled(!notselected);
            ERrbNMType.setEnabled(!notselected);
            ERtxtN.setEnabled(!notselected);
            ERtxtM.setEnabled(!notselected);
            ERtxtP.setEnabled(!notselected);
        }
    }//GEN-LAST:event_multiCheckActionPerformed

    private void BACheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BACheckActionPerformed

    private void ERhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERhelpActionPerformed
        showInfo("Erdõs–Rényi model",
                "Erdõs–Rényi model is the simplest version of random network generators. There are two distinct variants of the model:\n" +
"\n" +
"1. G(n,M) model takes as its input the number of nodes - n, and the number of edges - M. After generating n nodes, it adds M edges to the network, choosing the endpoints of each edge uniformly from n generated nodes.\n" +
"\n" +
"2. G(n,p) model also takes the number of nodes, but instade of the number of edges, it takes the probability of there being an edge between each pair of nodes. If p = 0, then M = 0. If p = 1, then M = n(n-1)/2.\n" +
"\n" +
"The main difference between these two variants is that in the first one, number of edges is set. Second model produces, on average, pn(n-1)/2 edges."
        );

        
    }//GEN-LAST:event_ERhelpActionPerformed

    private void WShelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WShelpActionPerformed
        showInfo("Watts-Strogatz model",
                "Watt-Strogatz model is one of the simplest models which gives rise to the so called small-world phenomenon. It takes three parameters:\n" +
"\n" +
"> N - number of nodes\n" +
"> K - mean node degree, must be even\n" +
"> ß - probability of edge rewireing\n" +
"\n" +
"Algorithm starts by constructing a regular ring lattice of N nodes, in which each node is connected to K other nodes on its sides (K/2 nodes on each side). If K = 2, this produces a standard cycle graph. Then, for each node n_i, with probability ß, algorithm rewires the edges connecting it with nodes n_j, j > i. Rewireing means that edge (n_i, n_j) becomes (n_i, n_k) where n_k is uniformly chosen so that i != k (to avoid self-loops) and n_k isn't already connected to n_i (to avoid double edges).\n" +
"\n" +
"For ß = 0, this model produces a regular ring lattice. For ß = 1, it produces a completly random graph, equivalent to Erdõs–Rényi G(n,M) model where n = N, M = NK/2."
        );
    }//GEN-LAST:event_WShelpActionPerformed

    private void BAHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAHelpActionPerformed
        showInfo("Barabási-Albert model ",
                "Barabasi-Albert model generates a scale-free network (meaning that it has a power-law degree distribution). Such networks are very often found real-world data, which makes this model useful. It takes three parameters:\n" +
"\n" +
"> N - total number of nodes\n" +
"> m0 << N - number of initial nodes\n" +
"> m <= m0 - initial node degree\n" +
"\n" +
"Algorithm begins by constructing a connected graph with m0 nodes and m*m0/2 edges (if m = m0, m(m0-1)/2 edges are constructed creating a complete graph). It then iterativly adds one node at a time until there are N nodes in total. Each new node has the initial degree of m. Its m neighbours are chosen with probability proportional to their degree. This type of node addition is called the \"preferential attachment\", meaning that the more connected a node is, the more likely it is to receive new neighbours."
        );
    }//GEN-LAST:event_BAHelpActionPerformed

    private void LATHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LATHelpActionPerformed
        showInfo("Lattice model", 
                "Lattice model creates an n-dimensional lattice.\n" +
"\n" +
"If the \"Generate torus\" feature is not selected, the model generates an n-dimensional hype rcube with a given set of edge lengths (dimension sizes). Nodes are connected if and only if their coordinates in the hyper cube are different by 1 in only one value, and equal in all the others. In other words, they are connected if and only if they share a common side.\n" +
"If the torus feature is selected, model generates an (n+1)-dimensional torus of the same sizes as the hype rcube would be. The only difference is that, with torus selected, opposite nodes are also connected.\n" +
"\n" +
"For example, if n = 1, torus feature would produce a cycle, while otherwise the model would produce a chain. If n = 2, torus produces a real torus, while otherwise model would produce a simple square lattice.\n" +
"\n" +
"Input is given in the form of comma-separated integers, all greater than one. For example, input \"3,2,3\", without the torus feature, produces a 3x2x3 cube."
        );
    }//GEN-LAST:event_LATHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BACheck;
    private javax.swing.JButton BAHelp;
    private javax.swing.JTextField BAtxtM;
    private javax.swing.JTextField BAtxtN;
    private javax.swing.JCheckBox ERCheck;
    private javax.swing.ButtonGroup ERGroup;
    private javax.swing.JPanel ERPanel;
    private javax.swing.JCheckBox ERRandomizeCurrent;
    private javax.swing.JButton ERhelp;
    private javax.swing.JRadioButton ERrbNMType;
    private javax.swing.JRadioButton ERrbNpType;
    private javax.swing.JTextField ERtxtM;
    private javax.swing.JTextField ERtxtN;
    private javax.swing.JTextField ERtxtP;
    private javax.swing.JButton ExitButton;
    private javax.swing.JCheckBox LATCheck;
    private javax.swing.JButton LATHelp;
    private javax.swing.JCheckBox LATisTorus;
    private javax.swing.JTextField LATtxtDimSizes;
    private javax.swing.JButton MULTIhelp;
    private javax.swing.JButton StartButton;
    private javax.swing.JCheckBox WSCheck;
    private javax.swing.JPanel WSPanel;
    private javax.swing.JPanel WSPanel1;
    private javax.swing.JPanel WSPanel2;
    private javax.swing.JButton WShelp;
    private javax.swing.JTextField WStxtBeta;
    private javax.swing.JTextField WStxtK;
    private javax.swing.JTextField WStxtN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblM1;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    private javax.swing.JLabel lblP4;
    private javax.swing.JCheckBox multiCheck;
    private javax.swing.JCheckBox multiIsDirected;
    private javax.swing.JPanel multiPanel;
    private javax.swing.JCheckBox multiRandomizeCurrent;
    // End of variables declaration//GEN-END:variables
/*public void endcalculus(int totalnodecount) {
        ProgressBar.setIndeterminate(false);
        ProgressLabel.setText("Finished: " + totalnodecount + " nodes worked");
    }

    public void stopcalculus() {
        ProgressBar.setIndeterminate(false);
        ProgressLabel.setText("Interrupted by user, click start to repeat");
        MULRun.setEnabled(true);
    }

    public void calculatingresult() {
        ProgressBar.setIndeterminate(true);
        ProgressBar.setVisible(true);
        ProgressLabel.setText("Calculating...");
        MULRun.setEnabled(false);
    }

    public void updatenodecounting(int nodeworked, int totalnodecount) {
        ProgressLabel.setText("Analysing node " + nodeworked + " of " + totalnodecount);
    }*/

    
    private void setERType(){
        if(ERrbNMType.isSelected()){
            ERtxtM.setEnabled(true);
            ERtxtP.setEnabled(false);
        }
        else{
            ERtxtM.setEnabled(false);
            ERtxtP.setEnabled(true);
        }
    }

    private void showInfo(String title, String info){
        JTextArea ta = new JTextArea(info,20,90);
        ta.setLineWrap(true);
        JOptionPane.showMessageDialog(this, new JScrollPane(ta), title, JOptionPane.PLAIN_MESSAGE);
    }
    
    public void closeRandomizer() {
        randomizerCore.closeOptionsMenu();
    }
    
    public boolean iscurrentnetworkchanged() {
        return false;
    }
    
    @Override
    public Component getComponent() {
        return this;
    }
    
    /*public void startcomputation() {
        calculatingresult();
        //currentnetwork = cyApplicationManager.getCurrentNetwork();
    }*/
    
    @Override
    public CytoPanelName getCytoPanelName() {
        return CytoPanelName.WEST;
    }
    @Override
    public String getTitle() {
        return "Randomizer";
    }
    
    @Override
    public Icon getIcon() { 
        return null;
    }


}
